name: Build WebTV APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extraer proyecto
        run: |
          unzip -q WebTV_Android_APK_READY.zip -d project

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar SDK Android
        run: |
          sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Compilar APK
        working-directory: project
        run: gradle assembleDebug --stacktrace

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: WebTV-APK
          path: project/app/build/outputs/apk/debug/app-debug.apk
